### PR TITLE
add Vocabulary

### PR DESCRIPTION
**Pull request by choosewhatulike**
Add Vocabulary for word and index one to one mapping

``` python
        vocab = Vocabulary()
        word_list = "this is a word list".split()
        vocab.update(word_list)
        vocab["word"] # get the index of "word"
        vocab.to_word(5) # get the word of index 5
  ```

### CODE REVIEW

**Comment by FengZiYjun** [comment]
@choosewhatulike 
One more thing:
The high-level API FastNLP in fastnlp.py relys on `word2id.pkl` and `id2label.pkl`. 
Changes should be made there as well.

**Comment by choosewhatulike** [comment]
ok, fixed now

**Comment by FengZiYjun** [comment]
@choosewhatulike 
If `self.word2idx = {}`, in `def __getitem__(self, w): `  `self.word2idx[DEFAULT_UNKNOWN_LABEL] ` will throw an error.

Is this an expected behavior ?

**Comment by choosewhatulike** [comment]
Well, The `need_default` is set to False when `self.word2idx = {}`, which means you are confident that there are no “out of vocabulary” when you indexing the words. So I think an exception is not wrong this time.

Think I need to add a more human readable exception.

**Pull request merged**
