### PR TITLE
change to tester and add multi-feature method and fix some bugs

### PR DESCRIPTION
**Pull request by h00Jiang**

### CODE REVIEW

**Comment by xuyige** [comment]
yes it is good
but still have some conflicts
@h00Jiang you can fork the newest version first, then run the code.
i think maybe some components have changed, like preprocess.py

**Comment by xuyige** [comment]
it didn't pass the test
@h00Jiang i change some code for passing conflict check. please check if i change the code into a wrong one.
@FengZiYjun maybe tester.py is been changed so it didn't pass the test, should we delete the test code for testing tester first?

**Comment by h00Jiang** [comment]
@xuyige which part is wrong?

**Comment by FengZiYjun** [comment]
A bug reported: in ClassificationTester, `self._model` has no loss defined. Please remove it.

**Comment by FengZiYjun** [comment]
@h00Jiang @xuyige 
The CI fails because `prediction = prediction.cpu().numpy()` is added in SeqLabelTester's evaluate function. 
CRF's viterbi_decode returns a list, rather than a tensor.

**Comment by xuyige** [comment]
@FengZiYjun 
i don't remember where to compute the loss in our former discussion, but i think a tester may not need to compute loss.
@h00Jiang 
i mean i have changed the code, but i am not sure if i change the code into wrong one. because i just   change the code for solving conflicts.

**Comment by h00Jiang** [comment]
@xuyige https://github.com/fastnlp/fastNLP/blob/4bcfc5f93085dfaf0f8902ae3c8af934a326115f/fastNLP/core/trainer.py#L147
https://github.com/fastnlp/fastNLP/blob/4bcfc5f93085dfaf0f8902ae3c8af934a326115f/fastNLP/core/trainer.py#L334
https://github.com/fastnlp/fastNLP/blob/4bcfc5f93085dfaf0f8902ae3c8af934a326115f/fastNLP/core/trainer.py#L147
in Trainer you can search "metric" , in Tester you can search "loss" and "metric"

**Comment by xpqiu** [comment]
The core is rewritten, so you need add this feature on the new code.

**Pull request closed without merging**
