### PR TITLE
CWS+POS tag interface

### PR DESCRIPTION
**Pull request by FengZiYjun**
CWS and POS tag can be done together. 
The model is `pos_tag_model_v_0.pkl`, trained by 人民日报标注集. 
Currently, you can download the models and pickle files from [复旦云分享链接](http://cloud.fudan.edu.cn/shareFolder/888380001/2mj4qqHJBpdNhl9T2).

## How to use ?
```python
nlp = FastNLP(model_dir=PATH_TO_POS_TAG_PICKLE_FILES)
nlp.load("pos_tag_model", config_file="pos_tag.config", section_name="pos_tag_model")
text = ["这是最好的基于深度学习的中文分词系统。",
            "大王叫我来巡山。",
            "我党多年来致力于改善人民生活水平。"]
results = nlp.run(text) 
for example in results:
    words, labels = [], []
    for res in example:
        words.append(res[0])
        labels.append(res[1])
    print(interpret_cws_pos_results(words, labels))
"""
[('这', 'r'), ('是', 'v'), ('最', 'd'), ('好', 'a'), ('的', 'u'), ('基于', 'p'), ('深度', 'd'), ('学习', 'v'), ('的', 'u'), ('中文', 'nz'), ('分词', 'vn'), ('系统', 'n'), ('。', 'w')]
[('大王', 'n'), ('叫', 'v'), ('我', 'r'), ('来', 'v'), ('巡山', 'ns'), ('。', 'w')]
[('我党', 'n'), ('多', 'a'), ('年', 'q'), ('来', 'f'), ('致力', 'v'), ('于', 'p'), ('改善', 'v'), ('人民', 'n'), ('生活', 'vn'), ('水平', 'n'), ('。', 'w')]
"""
```

### CODE REVIEW

**Comment by xuyige** [comment]
it shows "this branch has conflicts that must be resolved"

**Comment by keezen** [comment]
conflicts need to be fixed

**Comment by keezen** [comment]
conflicts need to be fixed

**Comment by FengZiYjun** [comment]
README updates to master. Conflict solved.

**Pull request merged**
