### PR TITLE
Chinese word segmentation interface

### PR DESCRIPTION
**Pull request by FengZiYjun**
The name of the model is `cws_basic_model`, which is `/home/zyfeng/fastNLP/reproduction/chinese_word_segment/save/cws_basic_model_v_0.pkl`. 
The training script is `fastNLP/reproduction/chinese_word_segment/run.py`. 

## How to use?
An example from `test/test_fastNLP.py`:

```Python
from fastNLP.fastnlp import FastNLP
from fastNLP.fastnlp import interpret_word_seg_results

PATH_TO_CWS_PICKLE_FILES = "/home/zyfeng/fastNLP/reproduction/chinese_word_segment/save/"

nlp = FastNLP(model_dir=PATH_TO_CWS_PICKLE_FILES)

nlp.load("cws_basic_model", config_file="cws.cfg", section_name="POS_test")

text = ["这是最好的基于深度学习的中文分词系统。",
            "大王叫我来巡山。",
            "我党多年来致力于改善人民生活水平。"]
results = nlp.run(text)

print(results)
# [[('这', 'S'), ('是', 'S'), ('最', 'S'), ('好', 'S'), ('的', 'S'), ('基', 'B'), ('于', 'E'), ('深', 'B'), ('度', 'E'), ('学', 'B'), ('习', 'E'), ('的', 'S'), ('中', 'B'), ('文', 'E'), ('分', 'B'), ('词', 'E'), ('系', 'B'), ('统', 'E'), ('。', 'S')], [('大', 'B'), ('王', 'E'), ('叫', 'S'), ('我', 'S'), ('来', 'S'), ('巡', 'B'), ('山', 'E'), ('。', 'S')], [('我', 'B'), ('党', 'E'), ('多', 'S'), ('年', 'S'), ('来', 'S'), ('致', 'B'), ('力', 'E'), ('于', 'S'), ('改', 'B'), ('善', 'E'), ('人', 'B'), ('民', 'E'), ('生', 'B'), ('活', 'E'), ('水', 'B'), ('平', 'E'), ('。', 'S')]]

for example in results:
    words, labels = [], []
    for res in example:
        words.append(res[0])
        labels.append(res[1])
    print(interpret_word_seg_results(words, labels))
"""
['这', '是', '最', '好', '的', '基于', '深度', '学习', '的', '中文', '分词', '系统', '。']
['大王', '叫', '我', '来', '巡山', '。']
['我党', '多', '年', '来', '致力', '于', '改善', '人民', '生活', '水平', '。']
"""
```

### CODE REVIEW

**Comment by FengZiYjun** [comment]
## Other Changes
1. Tester has a parameter "print_every_step" to control printing. print_every_step == 0 means NO print.
```Python
if self.print_every_step > 0 and step % self.print_every_step == 0:
    # print something
```
3. Trainer also has a parameter "print_every_step". The same usage.
2. Tester's evaluate return (list of) floats, rather than torch.cuda.tensor. (only for seqLabel now)
4. In training, validation steps are not shown. This is done by setting validator's print_every_step == 0.
5. Improve code comments.
6. Update interpret_word_seg_results in fastnlp.py. 
```python
def interpret_word_seg_results(char_seq, label_seq):
    """Transform model output into user-friendly contents.

    Example: In CWS, convert <BMES> labeling into segmented text.
    :param char_seq: list of string,
    :param label_seq: list of string, the same length as char_seq
            Each entry is one of ('B', 'M', 'E', 'S').
    :return output: list of words
    """
```
7. Delete useless data to increase git clone speed

**Comment by keezen** [comment]
nice, agree to merge

**Comment by xpqiu** [comment]
BMES should not be exposed to user.  Please refer the spacy-style output.

**Comment by FengZiYjun** [comment]
@xpqiu OK

**Pull request merged**
